{
  "language": "dart",
  "os": [
    "linux"
  ],
  "dist": "xenial",
  "addons": {
    "apt": {
      "packages": [
        "lib32stdc++6"
      ]
    }
  },
  "install": [
    "git clone https://github.com/flutter/flutter.git -b stable",
    "./flutter/bin/flutter doctor"
  ],
  "script": [
    "./flutter/bin/flutter test"
  ],
  "deploy": [
    {
      "provider": "pages",
      "strategy": "git",
      "on": {
        "branch": [
          "drewdev"
        ]
      },
      "cleanup": true,
      "token": "$GITHUB_TOKEN"
    }
  ],
  "cache": {
    "directories": [
      "$HOME/.pub-cache"
    ]
  }
}