// Mocks generated by Mockito 5.4.3 from annotations
// in talawa/test/views/join_org_after_auth/access_request_screen_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i7;
import 'dart:ui' as _i8;

import 'package:flutter/cupertino.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i5;
import 'package:talawa/enums/enums.dart' as _i6;
import 'package:talawa/models/organization/org_info.dart' as _i2;
import 'package:talawa/view_model/access_request_view_model.dart' as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeOrgInfo_0 extends _i1.SmartFake implements _i2.OrgInfo {
  _FakeOrgInfo_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeTextEditingController_1 extends _i1.SmartFake
    implements _i3.TextEditingController {
  _FakeTextEditingController_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [AccessScreenViewModel].
///
/// See the documentation for Mockito's code generation for more information.
class MockAccessScreenViewModel extends _i1.Mock
    implements _i4.AccessScreenViewModel {
  MockAccessScreenViewModel() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.OrgInfo get selectedOrganization => (super.noSuchMethod(
        Invocation.getter(#selectedOrganization),
        returnValue: _FakeOrgInfo_0(
          this,
          Invocation.getter(#selectedOrganization),
        ),
      ) as _i2.OrgInfo);

  @override
  set selectedOrganization(_i2.OrgInfo? _selectedOrganization) =>
      super.noSuchMethod(
        Invocation.setter(
          #selectedOrganization,
          _selectedOrganization,
        ),
        returnValueForMissingStub: null,
      );

  @override
  List<_i2.OrgInfo> get organizations => (super.noSuchMethod(
        Invocation.getter(#organizations),
        returnValue: <_i2.OrgInfo>[],
      ) as List<_i2.OrgInfo>);

  @override
  set organizations(List<_i2.OrgInfo>? _organizations) => super.noSuchMethod(
        Invocation.setter(
          #organizations,
          _organizations,
        ),
        returnValueForMissingStub: null,
      );

  @override
  String get orgId => (super.noSuchMethod(
        Invocation.getter(#orgId),
        returnValue: _i5.dummyValue<String>(
          this,
          Invocation.getter(#orgId),
        ),
      ) as String);

  @override
  set orgId(String? _orgId) => super.noSuchMethod(
        Invocation.setter(
          #orgId,
          _orgId,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i3.TextEditingController get optionalMessageController =>
      (super.noSuchMethod(
        Invocation.getter(#optionalMessageController),
        returnValue: _FakeTextEditingController_1(
          this,
          Invocation.getter(#optionalMessageController),
        ),
      ) as _i3.TextEditingController);

  @override
  _i6.ViewState get state => (super.noSuchMethod(
        Invocation.getter(#state),
        returnValue: _i6.ViewState.idle,
      ) as _i6.ViewState);

  @override
  bool get isBusy => (super.noSuchMethod(
        Invocation.getter(#isBusy),
        returnValue: false,
      ) as bool);

  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
      ) as bool);

  @override
  _i7.Future<void> initialise(_i2.OrgInfo? org) => (super.noSuchMethod(
        Invocation.method(
          #initialise,
          [org],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> sendMembershipRequest() => (super.noSuchMethod(
        Invocation.method(
          #sendMembershipRequest,
          [],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  void setState(_i6.ViewState? viewState) => super.noSuchMethod(
        Invocation.method(
          #setState,
          [viewState],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void addListener(_i8.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeListener(_i8.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );
}
