import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  tutorialSidebar: [
    'docs/introduction',
    {
      type: 'category',
      label: 'Getting Started',
      collapsed: false,
      items: [{ type: 'autogenerated', dirName: 'docs/getting-started' }],
    },

    {
      type: 'category',
      label: 'Developer Resources',
      items: [
        {
          type: 'category',
          label: 'Getting Started',
          collapsed: true,
          items: [
            {
              type: 'autogenerated',
              dirName: 'docs/developer-resources/getting-started',
            },
          ],
        },

        {
          type: 'category',
          label: 'Testing',
          collapsed: true,
          items: [
            {
              type: 'autogenerated',
              dirName: 'docs/developer-resources/testing',
            },
          ],
        },

        {
          type: 'category',
          label: 'Admin',
          collapsed: true,
          items: [
            {
              type: 'autogenerated',
              dirName: 'docs/developer-resources/admin',
            },
          ],
        },
        {
          type: 'category',
          label: 'API',
          collapsed: true,
          items: [
            {
              type: 'autogenerated',
              dirName: 'docs/developer-resources/api',
            },
          ],
        },
        {
          type: 'category',
          label: 'Mobile',
          collapsed: true,
          items: [
            {
              type: 'autogenerated',
              dirName: 'docs/developer-resources/app',
            },
          ],
        },
      ],
    },

    {
      type: 'category',
      label: 'Code Documentation',
      items: [{ type: 'autogenerated', dirName: 'auto-docs' }],
    },
  ],
};

export default sidebars;
