#!/bin/sh

# Check if any Dart files have changed
if git diff --name-only --cached | grep -q '\.dart$'; then
  echo "Dart files changed. Generating docs..."
  
  # Run the Generate Docs script
  scripts/docusaurus/generate_docs.sh
  
  # Add the generated docs to the commit
  git add docs/docs/auto-docs
else
  echo "No Dart files changed. Skipping doc generation."
fi

